# This is a basic workflow to check python types

name: CI-Checks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v2
    # Set up Python 
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    # Install packages
    - run: pip install --upgrade pip
    - run: pip install mypy==0.971 pipenv pytest
    # Type checking with mypy
    - run: mypy --strict $(git ls-files '*.py') --ignore-missing-imports
    # Test with pytest
    - run: |
          pipenv install --dev
          pipenv run pytest app/.



